name: Publish Docker

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

     - name: "Checkout repository"
       uses: actions/checkout@v3
       with:
        ref: 'master'

     - name: "Set up QEMU"
       uses: docker/setup-qemu-action@v2

     - name: "Set up Docker Buildx"
       uses: docker/setup-buildx-action@v1


     - name: "Login to GitHub Registry"
       env:
        REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
       uses: docker/login-action@v2

       with:
        
        registry: ghcr.io
        username: ${{ github.actor }}
        password: "${{ secrets.REGISTRY_TOKEN }}"

     - name: "Build & deploy db"
       uses: docker/build-push-action@v2
       with:
        push: true
        context: .
        file: ./docker/db/db.docker
        tags: "develop"

     - name: "Build & deploy app"
       uses: docker/build-push-action@v2
       with:
        push: true
        context: .
        file: ./docker/app/app.docker
        tags: "develop"